#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Ubuntu (32bit with mit-os), with Linux 3.8.0-35-generic' --class ubuntu --class gnu-linux --class gnu --class os {
        recordfail
        gfxmode $linux_gfx_mode
        insmod gzio
        insmod part_gpt
        insmod ext2
        set root='(hd0,gpt11)'
        search --no-floppy --fs-uuid --set=root f1df61f0-f012-499c-986a-1c152d6e0265
        linux   /boot/vmlinuz-3.8.0-35-generic root=UUID=f1df61f0-f012-499c-986a-1c152d6e0265 ro   quiet splash $vt_handoff
        initrd  /boot/initrd.img-3.8.0-35-generic
}
menuentry "Ubuntu (64bit), with Linux 3.8.0-29-generic (on /dev/sda2)" --class gnu-linux --class gnu --class os {
        insmod part_gpt
        insmod ext2
        set root='(hd0,gpt4)'
        search --no-floppy --fs-uuid --set=root 5cd66231-ad05-4e18-b743-cf210cebde5a
        linux /vmlinuz-3.8.0-29-generic root=UUID=8aee2f26-e533-4bee-9a39-c16712a4ce1f ro quiet splash $vt_handoff
        initrd /initrd.img-3.8.0-29-generic
}
menuentry "(hd0, gpt2) Chain Loader (second virtual hard disk)" {
    insmod ext2
    set root='(hd0,2)'
    search --no-floppy --fs-uuid --set 8aee2f26-e533-4bee-9a39-c16712a4ce1f
    chainloader +1
}
menuentry "(hd0, gpt4) Chain Loader (second virtual hard disk)" {
    insmod ext2
    set root='(hd0,4)'
    search --no-floppy --fs-uuid --set 5cd66231-ad05-4e18-b743-cf210cebde5a
    chainloader +1
}
menuentry "(hd0, gpt5) Chain Loader (second virtual hard disk)" {
    insmod ext2
    set root='(hd0,5)'
    search --no-floppy --fs-uuid --set 95d97624-8025-4bd8-9979-75fd1b5d2542
    chainloader +1
}
menuentry "(hd0, gpt6) Chain Loader (second virtual hard disk)" {
    insmod ext2
    set root='(hd0,6)'
    search --no-floppy --fs-uuid --set 6558d936-3875-44a8-b2cd-f50a8e45d5ff
    chainloader +1
}
menuentry "(hd0, gpt7) Chain Loader (second virtual hard disk)" {
    insmod ext2
    set root='(hd0,7)'
    search --no-floppy --fs-uuid --set 7a1e340f-41c8-423b-873f-dc12ede7ec08
    chainloader +1
}
menuentry "(hd0, gpt8) Chain Loader (second virtual hard disk)" {
    insmod ext2
    set root='(hd0,8)'
    search --no-floppy --fs-uuid --set 5e192234-4701-4f22-ab80-166292f6f5dc
    chainloader +1
}
menuentry "(hd0, gpt11) Chain Loader (second virtual hard disk)" {
    insmod ext2
    set root='(hd0,11)'
    search --no-floppy --fs-uuid --set f1df61f0-f012-499c-986a-1c152d6e0265
    chainloader +1
}
menuentry "(hd0, gpt13) Chain Loader (second virtual hard disk)" {
    insmod ext2
    set root='(hd0,13)'
    search --no-floppy --fs-uuid --set a3d64716-9965-4988-959e-f6168aa226f7
    chainloader +1
}

